// Comprehensive sample vocabulary data for testing
// 50+ words with full metadata, forms, examples, and relationships

export const SAMPLE_VOCAB = [
  {
    word: "Eloquent",
    definition: "Fluent or persuasive in speaking or writing; expressive",
    root: "eloqui (Latin) - to speak out",
    forms: {
      noun: "eloquence",
      verb: "",
      adjective: "eloquent",
      adverb: "eloquently",
    },
    examples: {
      base: "The eloquent speaker captivated the entire audience with her words.",
      noun: "Her eloquence was evident in every speech she delivered.",
      verb: "",
      adjective: "He gave an eloquent presentation on climate change.",
      adverb: "She spoke eloquently about the importance of education.",
    },
    synonyms: ["articulate", "expressive", "fluent", "verbose"],
    antonyms: ["inarticulate", "silent", "incoherent"],
    relatedWords: ["rhetoric", "oratory", "elocution", "discourse"],
    tags: ["Communication", "Advanced", "Speaking"],
  },
  {
    word: "Ephemeral",
    definition: "Lasting for a very short time; transitory",
    root: "ephemera (Greek) - lasting only a day",
    forms: {
      noun: "ephemeralness",
      verb: "",
      adjective: "ephemeral",
      adverb: "ephemerally",
    },
    examples: {
      base: "The beauty of cherry blossoms is ephemeral, lasting only weeks.",
      noun: "The ephemeralness of life reminds us to cherish each moment.",
      verb: "",
      adjective: "These trends are often ephemeral in nature.",
      adverb: "Social media trends come and go ephemerally.",
    },
    synonyms: ["transient", "fleeting", "temporary", "momentary"],
    antonyms: ["permanent", "eternal", "lasting", "enduring"],
    relatedWords: ["transient", "temporal", "evanescent", "fugitive"],
    tags: ["Time", "Advanced", "Literary"],
  },
  {
    word: "Pragmatic",
    definition:
      "Dealing with things in a practical, realistic way based on actual circumstances rather than theory",
    root: "pragma (Greek) - deed, act",
    forms: {
      noun: "pragmatism",
      verb: "",
      adjective: "pragmatic",
      adverb: "pragmatically",
    },
    examples: {
      base: "We need a pragmatic approach to solving this problem.",
      noun: "His pragmatism helped the company succeed despite challenges.",
      verb: "",
      adjective: "A pragmatic businesswoman focuses on results.",
      adverb: "She pragmatically solved the supply chain issue.",
    },
    synonyms: ["practical", "realistic", "sensible", "down-to-earth"],
    antonyms: ["idealistic", "theoretical", "impractical", "romantic"],
    relatedWords: ["practical", "utilitarian", "expedient", "realistic"],
    tags: ["Business", "Personality", "Intermediate"],
  },
  {
    word: "Meticulous",
    definition: "Showing great attention to detail; very careful and precise",
    root: "meticulosus (Latin) - fearful",
    forms: {
      noun: "meticulousness",
      verb: "",
      adjective: "meticulous",
      adverb: "meticulously",
    },
    examples: {
      base: "The architect's meticulous planning ensured the building's success.",
      noun: "Her meticulousness in research produced groundbreaking results.",
      verb: "",
      adjective: "He is meticulous about maintaining his workspace.",
      adverb: "The surgeon meticulously performed the complex operation.",
    },
    synonyms: ["careful", "precise", "thorough", "scrupulous"],
    antonyms: ["careless", "sloppy", "reckless", "negligent"],
    relatedWords: ["diligent", "fastidious", "conscientious", "punctilious"],
    tags: ["Personality", "Work", "Positive"],
  },
  {
    word: "Resilient",
    definition: "Able to recover quickly from difficulties; tough and flexible",
    root: "resilire (Latin) - to jump back",
    forms: {
      noun: "resilience",
      verb: "resiliate",
      adjective: "resilient",
      adverb: "resiliently",
    },
    examples: {
      base: "Communities showed resilient spirit after the natural disaster.",
      noun: "The resilience of the human spirit is truly remarkable.",
      verb: "The ecosystem resiliated to environmental changes.",
      adjective: "Bamboo is physically resilient and bends without breaking.",
      adverb: "She resiliently bounced back from her illness.",
    },
    synonyms: ["adaptable", "tough", "strong", "flexible"],
    antonyms: ["fragile", "vulnerable", "weak", "rigid"],
    relatedWords: ["adaptable", "durable", "robust", "steadfast"],
    tags: ["Personality", "Psychology", "Positive"],
  },
  {
    word: "Ambiguous",
    definition:
      "Having more than one possible meaning or interpretation; unclear",
    root: "ambiguus (Latin) - wavering, uncertain",
    forms: {
      noun: "ambiguity",
      verb: "",
      adjective: "ambiguous",
      adverb: "ambiguously",
    },
    examples: {
      base: "The author intentionally used ambiguous language in the novel.",
      noun: "The ambiguity of his response made everyone confused.",
      verb: "",
      adjective: "The contract contained ambiguous terms.",
      adverb: "He ambiguously referred to their relationship.",
    },
    synonyms: ["unclear", "vague", "equivocal", "indefinite"],
    antonyms: ["clear", "unambiguous", "definite", "explicit"],
    relatedWords: ["vague", "obscure", "indistinct", "nebulous"],
    tags: ["Language", "Writing", "Intermediate"],
  },
  {
    word: "Ubiquitous",
    definition: "Present, appearing, or found everywhere",
    root: "ubique (Latin) - everywhere",
    forms: {
      noun: "ubiquity",
      verb: "",
      adjective: "ubiquitous",
      adverb: "ubiquitously",
    },
    examples: {
      base: "Smartphones have become ubiquitous in modern society.",
      noun: "The ubiquity of social media shapes how we communicate.",
      verb: "",
      adjective: "Plastic bags are ubiquitous in shopping centers.",
      adverb:
        "Internet connectivity is ubiquitously available in developed nations.",
    },
    synonyms: ["omnipresent", "pervasive", "universal", "common"],
    antonyms: ["rare", "scarce", "limited", "localized"],
    relatedWords: ["omnipresent", "pervasive", "pandemic", "rampant"],
    tags: ["Modern", "Technology", "Advanced"],
  },
  {
    word: "Vindicate",
    definition:
      "To clear someone of blame or suspicion; to prove to be correct",
    root: "vindicare (Latin) - to claim, avenge",
    forms: {
      noun: "vindication",
      verb: "vindicate",
      adjective: "vindicated",
      adverb: "vindicatively",
    },
    examples: {
      base: "The evidence vindicated the defendant in the trial.",
      noun: "His vindication came after years of struggle.",
      verb: "The successful launch vindicated her business strategy.",
      adjective: "The vindicated scientist finally gained recognition.",
      adverb: "She vindicatively proved her innocence.",
    },
    synonyms: ["exonerate", "clear", "justify", "validate"],
    antonyms: ["incriminate", "condemn", "blame", "accuse"],
    relatedWords: ["exonerate", "justify", "absolve", "acquit"],
    tags: ["Justice", "Legal", "Advanced"],
  },
  {
    word: "Pensive",
    definition: "Thinking deeply about something; thoughtful or melancholy",
    root: "pensare (Latin) - to think, weigh",
    forms: {
      noun: "pensiveness",
      verb: "",
      adjective: "pensive",
      adverb: "pensively",
    },
    examples: {
      base: "She was in a pensive mood while watching the sunset.",
      noun: "His pensiveness suggested he was troubled.",
      verb: "",
      adjective: "The pensive atmosphere of the library suited his work.",
      adverb: "He pensively gazed out the window.",
    },
    synonyms: ["thoughtful", "reflective", "contemplative", "meditative"],
    antonyms: ["cheerful", "carefree", "frivolous", "lighthearted"],
    relatedWords: [
      "contemplative",
      "reflective",
      "introspective",
      "meditative",
    ],
    tags: ["Emotion", "Personality", "Intermediate"],
  },
  {
    word: "Tenacious",
    definition: "Holding firmly to something; persistent and determined",
    root: "tenere (Latin) - to hold",
    forms: {
      noun: "tenacity",
      verb: "",
      adjective: "tenacious",
      adverb: "tenaciously",
    },
    examples: {
      base: "His tenacious efforts finally paid off when he won the championship.",
      noun: "Her tenacity in pursuing her dreams inspired everyone.",
      verb: "",
      adjective: "A tenacious grip kept him from falling.",
      adverb: "She tenaciously held onto her beliefs.",
    },
    synonyms: ["persistent", "determined", "stubborn", "steadfast"],
    antonyms: ["weak", "irresolute", "yielding", "uncertain"],
    relatedWords: ["persistent", "steadfast", "resolute", "determined"],
    tags: ["Personality", "Work", "Positive"],
  },
  {
    word: "Placate",
    definition: "To calm or soothe someone who is angry; to appease",
    root: "placare (Latin) - to calm",
    forms: {
      noun: "placation",
      verb: "placate",
      adjective: "placated",
      adverb: "placatingly",
    },
    examples: {
      base: "He tried to placate the angry customer with an apology.",
      noun: "The placation of the protest required negotiations.",
      verb: "Money alone cannot placate moral outrage.",
      adjective: "The placated audience applauded the actor.",
      adverb: "She spoke placatingly to ease the tension.",
    },
    synonyms: ["appease", "soothe", "calm", "mollify"],
    antonyms: ["provoke", "inflame", "anger", "agitate"],
    relatedWords: ["appease", "mollify", "conciliate", "soothe"],
    tags: ["Communication", "Emotion", "Intermediate"],
  },
  {
    word: "Lucid",
    definition: "Expressed clearly; easy to understand; mentally sharp",
    root: "lucidus (Latin) - clear, shining",
    forms: {
      noun: "lucidity",
      verb: "",
      adjective: "lucid",
      adverb: "lucidly",
    },
    examples: {
      base: "His lucid explanation made the complex topic understandable.",
      noun: "Her lucidity of thought impressed the selection committee.",
      verb: "",
      adjective: "A lucid mind is essential for good decision-making.",
      adverb: "He lucidly described the scientific process.",
    },
    synonyms: ["clear", "transparent", "intelligible", "comprehensible"],
    antonyms: ["unclear", "confusing", "opaque", "cryptic"],
    relatedWords: ["clear", "transparent", "explicit", "intelligible"],
    tags: ["Intelligence", "Communication", "Positive"],
  },
  {
    word: "Jocular",
    definition: "Meant to be humorous or funny; playful",
    root: "jocularis (Latin) - playful",
    forms: {
      noun: "jocularity",
      verb: "",
      adjective: "jocular",
      adverb: "jocularly",
    },
    examples: {
      base: "His jocular manner made the serious meeting more pleasant.",
      noun: "The jocularity of his comments lightened the mood.",
      verb: "",
      adjective: "She made a jocular remark that made everyone laugh.",
      adverb: "He jocularly tossed a quip to break the ice.",
    },
    synonyms: ["humorous", "funny", "joking", "playful"],
    antonyms: ["serious", "solemn", "grave", "stern"],
    relatedWords: ["humorous", "witty", "playful", "jovial"],
    tags: ["Humor", "Personality", "Communication"],
  },
  {
    word: "Enigmatic",
    definition: "Mysterious and difficult to understand; puzzling",
    root: "ainigma (Greek) - riddle",
    forms: {
      noun: "enigma",
      verb: "",
      adjective: "enigmatic",
      adverb: "enigmatically",
    },
    examples: {
      base: "The enigmatic smile of the Mona Lisa has fascinated people for centuries.",
      noun: "His behavior remained an enigma to his colleagues.",
      verb: "",
      adjective: "The CEO's enigmatic leadership style confused employees.",
      adverb: "She enigmatically refused to answer the question.",
    },
    synonyms: ["mysterious", "cryptic", "puzzling", "enigmatical"],
    antonyms: ["clear", "obvious", "transparent", "straightforward"],
    relatedWords: ["mysterious", "cryptic", "inscrutable", "unfathomable"],
    tags: ["Mystery", "Advanced", "Literary"],
  },
  {
    word: "Altruistic",
    definition: "Showing concern for others rather than for oneself; unselfish",
    root: "alter (Latin) - other",
    forms: {
      noun: "altruism",
      verb: "",
      adjective: "altruistic",
      adverb: "altruistically",
    },
    examples: {
      base: "Her altruistic work in the community earned her respect.",
      noun: "Altruism drives many volunteering organizations.",
      verb: "",
      adjective: "His altruistic nature made him donate to charities.",
      adverb: "She altruistically devoted her life to helping others.",
    },
    synonyms: ["selfless", "generous", "philanthropic", "unselfish"],
    antonyms: ["selfish", "egocentric", "greedy", "self-serving"],
    relatedWords: ["philanthropic", "generous", "selfless", "benevolent"],
    tags: ["Personality", "Ethics", "Positive"],
  },
  {
    word: "Proliferate",
    definition: "To increase rapidly in number; to spread quickly",
    root: "proles (Latin) - offspring, proliferi - to bear",
    forms: {
      noun: "proliferation",
      verb: "proliferate",
      adjective: "proliferating",
      adverb: "proliferatively",
    },
    examples: {
      base: "Fake news proliferated on social media during the election.",
      noun: "The proliferation of smartphones changed society.",
      verb: "The bacteria proliferates in warm, moist environments.",
      adjective: "Proliferating technologies reshape industries.",
      adverb: "Species proliferated diversely across the continent.",
    },
    synonyms: ["multiply", "increase", "spread", "expand"],
    antonyms: ["decrease", "diminish", "reduce", "decline"],
    relatedWords: ["multiply", "expand", "spread", "flourish"],
    tags: ["Science", "Growth", "Intermediate"],
  },
  {
    word: "Diligent",
    definition: "Having or showing care in one's work or duties; conscientious",
    root: "diligere (Latin) - to choose, value",
    forms: {
      noun: "diligence",
      verb: "",
      adjective: "diligent",
      adverb: "diligently",
    },
    examples: {
      base: "Her diligent work ethic made her a model employee.",
      noun: "Success requires diligence and determination.",
      verb: "",
      adjective: "Diligent students achieve better grades.",
      adverb: "He diligently studied for the examination.",
    },
    synonyms: ["careful", "conscientious", "industrious", "thorough"],
    antonyms: ["lazy", "careless", "negligent", "idle"],
    relatedWords: ["conscientious", "industrious", "meticulous", "dedicated"],
    tags: ["Work", "Personality", "Positive"],
  },
  {
    word: "Nostalgia",
    definition:
      "A sentimental longing for the past; wistfulness about former times",
    root: "nostos (Greek) - homecoming, algos - pain",
    forms: {
      noun: "nostalgia",
      verb: "",
      adjective: "nostalgic",
      adverb: "nostalgically",
    },
    examples: {
      base: "Hearing the old song filled him with nostalgia for his childhood.",
      noun: "The 1980s music inspires nostalgia in many adults.",
      verb: "",
      adjective: "Nostalgic movies appeal to older audiences.",
      adverb: "She nostalgically reminisced about her college days.",
    },
    synonyms: ["yearning", "longing", "sentimentality", "wistfulness"],
    antonyms: ["indifference", "apathy", "disinterest"],
    relatedWords: ["sentimental", "wistful", "yearning", "bittersweet"],
    tags: ["Emotion", "Time", "Intermediate"],
  },
  {
    word: "Benevolent",
    definition: "Showing kindness and generosity; charitable",
    root: "bene (Latin) - well, volens - wishing",
    forms: {
      noun: "benevolence",
      verb: "",
      adjective: "benevolent",
      adverb: "benevolently",
    },
    examples: {
      base: "The benevolent king used his wealth to help his subjects.",
      noun: "His benevolence toward employees created loyalty.",
      verb: "",
      adjective: "She had a benevolent attitude toward the homeless.",
      adverb: "He benevolently donated millions to the hospital.",
    },
    synonyms: ["kind", "generous", "charitable", "philanthropic"],
    antonyms: ["cruel", "mean", "malevolent", "selfish"],
    relatedWords: ["generous", "charitable", "philanthropic", "kind-hearted"],
    tags: ["Personality", "Ethics", "Positive"],
  },
  {
    word: "Pragmatism",
    definition:
      "A practical approach to problems and affairs; dealing with things in a realistic way",
    root: "pragma (Greek) - deed, act",
    forms: {
      noun: "pragmatism",
      verb: "",
      adjective: "pragmatic",
      adverb: "pragmatically",
    },
    examples: {
      base: "His pragmatism kept the company focused on profits.",
      noun: "Business pragmatism often conflicts with idealism.",
      verb: "",
      adjective: "The pragmatic solution was the most effective.",
      adverb: "She pragmatically evaluated the project's feasibility.",
    },
    synonyms: ["practicality", "realism", "common sense", "expediency"],
    antonyms: ["idealism", "romanticism", "impracticality", "theory"],
    relatedWords: ["practical", "realistic", "utilitarian", "expedient"],
    tags: ["Philosophy", "Business", "Advanced"],
  },
  {
    word: "Ephemera",
    definition:
      "Things that are ephemeral; collectible items of short-lived value",
    root: "ephemera (Greek) - lasting only a day",
    forms: {
      noun: "ephemera",
      verb: "",
      adjective: "ephemeral",
      adverb: "ephemerally",
    },
    examples: {
      base: "He collects vintage ephemera like old tickets and postcards.",
      noun: "Paper ephemera deteriorates over time without care.",
      verb: "",
      adjective: "The ephemeral nature of digital memes is ironic.",
      adverb: "Social trends last ephemerally, lasting weeks or months.",
    },
    synonyms: ["trinkets", "mementos", "momentos"],
    antonyms: ["permanences", "monuments", "artifacts"],
    relatedWords: ["transient", "temporary", "fleeting", "memorabilia"],
    tags: ["Collecting", "Time", "Advanced"],
  },
  {
    word: "Verbose",
    definition: "Using or containing more words than necessary; wordy",
    root: "verbosus (Latin) - talkative",
    forms: {
      noun: "verbosity",
      verb: "",
      adjective: "verbose",
      adverb: "verbosely",
    },
    examples: {
      base: "His verbose email was 10 pages longer than necessary.",
      noun: "The verbosity of legal documents confuses many people.",
      verb: "",
      adjective: "Avoid verbose language in professional writing.",
      adverb: "She verbosely explained every minor detail.",
    },
    synonyms: ["wordy", "long-winded", "talkative", "garrulous"],
    antonyms: ["concise", "brief", "laconic", "terse"],
    relatedWords: ["wordy", "long-winded", "prolix", "loquacious"],
    tags: ["Writing", "Communication", "Intermediate"],
  },
  {
    word: "Autonomy",
    definition:
      "Independence and self-governance; the right to make one's own decisions",
    root: "autos (Greek) - self, nomos - law",
    forms: {
      noun: "autonomy",
      verb: "",
      adjective: "autonomous",
      adverb: "autonomously",
    },
    examples: {
      base: "The university's autonomy allows it to set its own curricula.",
      noun: "Individual autonomy is a fundamental democratic principle.",
      verb: "",
      adjective: "Autonomous vehicles represent a technological breakthrough.",
      adverb: "She autonomously decided her career path.",
    },
    synonyms: ["independence", "freedom", "self-determination", "sovereignty"],
    antonyms: ["dependence", "control", "subjection", "constraint"],
    relatedWords: ["independent", "self-governed", "sovereign", "free"],
    tags: ["Politics", "Freedom", "Advanced"],
  },
  {
    word: "Cacophony",
    definition:
      "A harsh or discordant mixture of sounds; loud and unpleasant noise",
    root: "kakos (Greek) - bad, phone - sound",
    forms: {
      noun: "cacophony",
      verb: "",
      adjective: "cacophonous",
      adverb: "cacophonously",
    },
    examples: {
      base: "The cacophony of car horns filled the busy intersection.",
      noun: "The cacophony in the school cafeteria was overwhelming.",
      verb: "",
      adjective: "The cacophonous orchestra sounded completely out of tune.",
      adverb: "Instruments cacophonously clashed in discord.",
    },
    synonyms: ["discord", "noise", "din", "clamor"],
    antonyms: ["harmony", "melody", "symphony", "consonance"],
    relatedWords: ["discord", "noise", "dissonance", "clamor"],
    tags: ["Sound", "Music", "Advanced"],
  },
  {
    word: "Inconspicuous",
    definition: "Not clearly visible or attracting attention; unobtrusive",
    root: "in- (not), conspicuus (Latin) - visible, obvious",
    forms: {
      noun: "inconspicuousness",
      verb: "",
      adjective: "inconspicuous",
      adverb: "inconspicuously",
    },
    examples: {
      base: "She wore inconspicuous clothing to avoid attention.",
      noun: "His inconspicuousness made him easy to overlook.",
      verb: "",
      adjective: "The camera was inconspicuous, hidden among decorations.",
      adverb: "He inconspicuously left the party early.",
    },
    synonyms: ["unobtrusive", "subtle", "hidden", "discreet"],
    antonyms: ["conspicuous", "obvious", "visible", "prominent"],
    relatedWords: ["unobtrusive", "subtle", "discreet", "understated"],
    tags: ["Appearance", "Behavior", "Intermediate"],
  },
  {
    word: "Cogent",
    definition: "Appealing strongly to the mind or reason; convincing",
    root: "cogent (Latin) - driven together, compelling",
    forms: {
      noun: "cogency",
      verb: "",
      adjective: "cogent",
      adverb: "cogently",
    },
    examples: {
      base: "His cogent argument persuaded the jury.",
      noun: "The cogency of the evidence was undeniable.",
      verb: "",
      adjective: "A cogent reason for the delay was provided.",
      adverb: "She cogently explained why the policy change was necessary.",
    },
    synonyms: ["convincing", "compelling", "persuasive", "forceful"],
    antonyms: ["weak", "unconvincing", "feeble", "ineffective"],
    relatedWords: ["convincing", "compelling", "forceful", "powerful"],
    tags: ["Logic", "Arguments", "Advanced"],
  },
  {
    word: "Defunct",
    definition: "No longer existing or functioning; dead or obsolete",
    root: "defunctus (Latin) - finished, dead",
    forms: {
      noun: "defunct",
      verb: "",
      adjective: "defunct",
      adverb: "",
    },
    examples: {
      base: "Many defunct once-popular apps are forgotten today.",
      noun: "The defunct computer company was bought by a rival firm.",
      verb: "",
      adjective: "Defunct railroads once connected small towns.",
      adverb: "",
    },
    synonyms: ["dead", "extinct", "obsolete", "terminated"],
    antonyms: ["active", "functioning", "operational", "alive"],
    relatedWords: ["extinct", "obsolete", "dead", "inactive"],
    tags: ["State", "Time", "Intermediate"],
  },
  {
    word: "Esoteric",
    definition:
      "Intended for or likely to be understood by only a small number of people; mysterious",
    root: "esoteros (Greek) - inner, secret",
    forms: {
      noun: "esotericism",
      verb: "",
      adjective: "esoteric",
      adverb: "esoterically",
    },
    examples: {
      base: "The book discusses esoteric philosophical concepts.",
      noun: "The esotericism of the cult attracted few members.",
      verb: "",
      adjective: "Ancient esoteric knowledge was passed to few initiates.",
      adverb: "She esoterically referenced obscure historical events.",
    },
    synonyms: ["obscure", "cryptic", "mysterious", "specialized"],
    antonyms: ["obvious", "exoteric", "accessible", "popular"],
    relatedWords: ["obscure", "arcane", "cryptic", "mysterious"],
    tags: ["Knowledge", "Mystery", "Advanced"],
  },
  {
    word: "Euphoria",
    definition: "A state of intense happiness and well-being; exhilaration",
    root: "eu (Greek) - good, pherein - to bear",
    forms: {
      noun: "euphoria",
      verb: "",
      adjective: "euphoric",
      adverb: "euphorically",
    },
    examples: {
      base: "The team experienced euphoria after winning the championship.",
      noun: "The euphoria of victory was short-lived.",
      verb: "",
      adjective: "The euphoric fans celebrated in the streets.",
      adverb: "She euphorically danced with joy.",
    },
    synonyms: ["elation", "joy", "bliss", "exultation"],
    antonyms: ["depression", "sadness", "despair", "misery"],
    relatedWords: ["elation", "joy", "bliss", "ecstasy"],
    tags: ["Emotion", "Happiness", "Intermediate"],
  },
  {
    word: "Facilitate",
    definition: "To make something easier; to help bring about",
    root: "facilis (Latin) - easy",
    forms: {
      noun: "facilitation",
      verb: "facilitate",
      adjective: "facilitative",
      adverb: "facilitatively",
    },
    examples: {
      base: "Technology facilitates global communication.",
      noun: "Facilitation of the meeting required careful planning.",
      verb: "Good mentorship facilitates professional growth.",
      adjective: "A facilitative approach encourages participation.",
      adverb: "She facilitatively guided the group discussion.",
    },
    synonyms: ["ease", "help", "promote", "enable"],
    antonyms: ["hinder", "obstruct", "impede", "prevent"],
    relatedWords: ["aid", "assist", "enable", "promote"],
    tags: ["Help", "Work", "Positive"],
  },
  {
    word: "Gregarious",
    definition: "Fond of being with others; sociable; living in groups",
    root: "gregarius (Latin) - of a herd or flock",
    forms: {
      noun: "gregariousness",
      verb: "",
      adjective: "gregarious",
      adverb: "gregariously",
    },
    examples: {
      base: "Humans are gregarious creatures who thrive in communities.",
      noun: "His gregariousness made him popular at parties.",
      verb: "",
      adjective: "Zebras are gregarious animals that live in herds.",
      adverb: "She gregariously moved through the crowded room.",
    },
    synonyms: ["social", "sociable", "communal", "group-oriented"],
    antonyms: ["solitary", "antisocial", "withdrawn", "reclusive"],
    relatedWords: ["social", "communal", "sociable", "group-minded"],
    tags: ["Personality", "Social", "Positive"],
  },
  {
    word: "Homogeneous",
    definition: "Of the same or similar kind; consisting of identical elements",
    root: "homos (Greek) - same, genos - kind",
    forms: {
      noun: "homogeneity",
      verb: "",
      adjective: "homogeneous",
      adverb: "homogeneously",
    },
    examples: {
      base: "The class was relatively homogeneous in terms of age.",
      noun: "The homogeneity of the painting's color palette created unity.",
      verb: "",
      adjective: "A homogeneous mixture appears uniform throughout.",
      adverb: "The population distributed homogeneously across regions.",
    },
    synonyms: ["uniform", "identical", "similar", "consistent"],
    antonyms: ["heterogeneous", "diverse", "varied", "mixed"],
    relatedWords: ["uniform", "identical", "consistent", "alike"],
    tags: ["Science", "Composition", "Advanced"],
  },
  {
    word: "Impeccable",
    definition: "Flawless; without any defects or mistakes",
    root: "impecabilis (Latin) - not likely to sin",
    forms: {
      noun: "impeccability",
      verb: "",
      adjective: "impeccable",
      adverb: "impeccably",
    },
    examples: {
      base: "She maintained an impeccable record throughout her career.",
      noun: "The impeccability of his work earned industry recognition.",
      verb: "",
      adjective: "His impeccable manners impressed everyone.",
      adverb: "She impeccably executed the complex dance routine.",
    },
    synonyms: ["flawless", "perfect", "faultless", "immaculate"],
    antonyms: ["flawed", "imperfect", "defective", "faulty"],
    relatedWords: ["flawless", "perfect", "immaculate", "pristine"],
    tags: ["Quality", "Personality", "Positive"],
  },
  {
    word: "Inchoate",
    definition: "Just begun; in an early stage of development; incomplete",
    root: "incohatus (Latin) - just begun",
    forms: {
      noun: "inchoateness",
      verb: "inchoate",
      adjective: "inchoate",
      adverb: "inchoately",
    },
    examples: {
      base: "The inchoate plans needed further development before presentation.",
      noun: "The inchoateness of the idea made it difficult to explain.",
      verb: "The project inchoated with brainstorming sessions.",
      adjective: "His inchoate thoughts were scattered and unfocused.",
      adverb: "She inchoately described her vision.",
    },
    synonyms: ["incomplete", "unfinished", "rough", "preliminary"],
    antonyms: ["complete", "finished", "developed", "mature"],
    relatedWords: ["incomplete", "preliminary", "rudimentary", "nascent"],
    tags: ["Development", "Time", "Advanced"],
  },
  {
    word: "Laconic",
    definition: "Using very few words; brief and to the point",
    root: "Lakonikos (Greek) - from Laconia, home of Sparta",
    forms: {
      noun: "laconicism",
      verb: "",
      adjective: "laconic",
      adverb: "laconically",
    },
    examples: {
      base: "Her laconic response left everyone wanting more details.",
      noun: "The laconicism of his speech style was memorable.",
      verb: "",
      adjective: "A laconic speaker often has more impact.",
      adverb: "He laconically replied, 'No.'",
    },
    synonyms: ["brief", "terse", "concise", "succinct"],
    antonyms: ["verbose", "wordy", "talkative", "long-winded"],
    relatedWords: ["concise", "terse", "succinct", "brief"],
    tags: ["Communication", "Writing", "Intermediate"],
  },
  {
    word: "Mendacious",
    definition: "Given to or characterized by deception or lying; dishonest",
    root: "mendacium (Latin) - lie",
    forms: {
      noun: "mendacity",
      verb: "",
      adjective: "mendacious",
      adverb: "mendaciously",
    },
    examples: {
      base: "The mendacious claims in the advertisement misled consumers.",
      noun: "His mendacity became apparent over time.",
      verb: "",
      adjective: "The mendacious witness contradicted himself.",
      adverb: "He mendaciously denied the allegations.",
    },
    synonyms: ["dishonest", "deceitful", "lying", "fraudulent"],
    antonyms: ["truthful", "honest", "sincere", "veracious"],
    relatedWords: ["dishonest", "deceitful", "fraudulent", "false"],
    tags: ["Character", "Morality", "Negative"],
  },
  {
    word: "Obfuscate",
    definition: "To make something unclear or obscure; to confuse",
    root: "obfuscare (Latin) - to darken",
    forms: {
      noun: "obfuscation",
      verb: "obfuscate",
      adjective: "obfuscatory",
      adverb: "obfuscatingly",
    },
    examples: {
      base: "The complex legal language obfuscated the contract's terms.",
      noun: "The obfuscation of the facts confused the public.",
      verb: "Deliberately obfuscating the truth is unethical.",
      adjective: "His obfuscatory explanation raised more questions.",
      adverb: "She obfuscatingly avoided the real issue.",
    },
    synonyms: ["obscure", "confuse", "cloud", "muddy"],
    antonyms: ["clarify", "explain", "illuminate", "elucidate"],
    relatedWords: ["obscure", "confuse", "cloud", "muddy"],
    tags: ["Communication", "Behavior", "Negative"],
  },
  {
    word: "Perspicacious",
    definition: "Having keen insight and understanding; mentally sharp",
    root: "perspicere (Latin) - to see through, understand",
    forms: {
      noun: "perspicacity",
      verb: "",
      adjective: "perspicacious",
      adverb: "perspicaciously",
    },
    examples: {
      base: "Her perspicacious analysis identified the root cause immediately.",
      noun: "His perspicacity in business made him successful.",
      verb: "",
      adjective: "A perspicacious observer notices subtle details.",
      adverb: "She perspicaciously predicted the market crash.",
    },
    synonyms: ["insightful", "perceptive", "shrewd", "astute"],
    antonyms: ["dull", "obtuse", "blind", "insensitive"],
    relatedWords: ["insightful", "perceptive", "shrewd", "astute"],
    tags: ["Intelligence", "Perception", "Positive"],
  },
  {
    word: "Querulous",
    definition: "Complaining and whining; prone to making petty complaints",
    root: "querulus (Latin) - complaining",
    forms: {
      noun: "querulousness",
      verb: "",
      adjective: "querulous",
      adverb: "querulously",
    },
    examples: {
      base: "His querulous tone annoyed everyone in the meeting.",
      noun: "The customer's querulousness finally drove away all business.",
      verb: "",
      adjective: "A querulous attitude spreads negativity.",
      adverb: "She querulously complained about the weather.",
    },
    synonyms: ["complaining", "whining", "petulant", "irritable"],
    antonyms: ["content", "satisfied", "cheerful", "uncomplaining"],
    relatedWords: ["complaining", "whining", "petulant", "irritable"],
    tags: ["Personality", "Negative", "Behavior"],
  },
  {
    word: "Recalcitrant",
    definition: "Resisting authority or control; stubbornly defiant",
    root: "recalcitrare (Latin) - to kick against",
    forms: {
      noun: "recalcitrance",
      verb: "",
      adjective: "recalcitrant",
      adverb: "recalcitrantly",
    },
    examples: {
      base: "The recalcitrant employee refused to follow the new procedures.",
      noun: "His recalcitrance led to his dismissal.",
      verb: "",
      adjective: "A recalcitrant student disrupts the classroom.",
      adverb: "She recalcitrantly opposed every suggestion.",
    },
    synonyms: ["defiant", "stubborn", "obstinate", "disobedient"],
    antonyms: ["obedient", "compliant", "cooperative", "submissive"],
    relatedWords: ["defiant", "stubborn", "obstinate", "unruly"],
    tags: ["Behavior", "Personality", "Negative"],
  },
  {
    word: "Sagacious",
    definition: "Having keen mental judgment and understanding; wise",
    root: "sagire (Latin) - to perceive quickly",
    forms: {
      noun: "sagacity",
      verb: "",
      adjective: "sagacious",
      adverb: "sagaciously",
    },
    examples: {
      base: "The sagacious leader made decisions based on long-term vision.",
      noun: "Her sagacity in negotiations earned industry respect.",
      verb: "",
      adjective: "Sagacious advice is worth its weight in gold.",
      adverb: "He sagaciously invested before the market boom.",
    },
    synonyms: ["wise", "shrewd", "discerning", "intelligent"],
    antonyms: ["foolish", "naive", "stupid", "unwise"],
    relatedWords: ["wise", "shrewd", "discerning", "intelligent"],
    tags: ["Intelligence", "Wisdom", "Positive"],
  },
  {
    word: "Sanguine",
    definition: "Optimistic and positive; hopeful; also, blood-red in color",
    root: "sanguineus (Latin) - bloody, of blood",
    forms: {
      noun: "sanguinity",
      verb: "",
      adjective: "sanguine",
      adverb: "sanguinely",
    },
    examples: {
      base: "Despite setbacks, she maintained a sanguine outlook.",
      noun: "His sanguinity about the future inspired confidence.",
      verb: "",
      adjective: "A sanguine temperament helps overcome challenges.",
      adverb: "He sanguinely believed everything would work out.",
    },
    synonyms: ["optimistic", "hopeful", "positive", "confident"],
    antonyms: ["pessimistic", "negative", "doubtful", "fearful"],
    relatedWords: ["optimistic", "hopeful", "positive", "confident"],
    tags: ["Personality", "Emotion", "Positive"],
  },
  {
    word: "Serendipitous",
    definition: "Occurring by chance in a happy or beneficial way; fortunate",
    root: "Serendip (Arabic name for Sri Lanka) + -ity",
    forms: {
      noun: "serendipity",
      verb: "",
      adjective: "serendipitous",
      adverb: "serendipitously",
    },
    examples: {
      base: "The serendipitous meeting led to a business partnership.",
      noun: "It was pure serendipity that she found the lost letter.",
      verb: "",
      adjective: "A serendipitous discovery changed the course of history.",
      adverb: "They serendipitously encountered each other after years.",
    },
    synonyms: ["fortunate", "lucky", "chance", "felicitous"],
    antonyms: ["unlucky", "unfortunate", "planned", "intentional"],
    relatedWords: ["fortunate", "lucky", "chance", "felicitous"],
    tags: ["Luck", "Fortune", "Positive"],
  },
  {
    word: "Temerity",
    definition: "Excessive boldness or audacity; reckless daring",
    root: "temeritas (Latin) - rashness",
    forms: {
      noun: "temerity",
      verb: "",
      adjective: "rash",
      adverb: "rashly",
    },
    examples: {
      base: "He had the temerity to argue with the referee.",
      noun: "Her temerity in challenging the boss impressed some coworkers.",
      verb: "",
      adjective: "Such a rash decision could have consequences.",
      adverb: "He rashly invested all his savings.",
    },
    synonyms: ["boldness", "audacity", "daring", "nerve"],
    antonyms: ["timidity", "caution", "restraint", "cowardice"],
    relatedWords: ["boldness", "audacity", "daring", "nerve"],
    tags: ["Personality", "Behavior", "Negative"],
  },
  {
    word: "Ubiquitous",
    definition: "Present, appearing, or found everywhere",
    root: "ubique (Latin) - everywhere",
    forms: {
      noun: "ubiquity",
      verb: "",
      adjective: "ubiquitous",
      adverb: "ubiquitously",
    },
    examples: {
      base: "Coffee culture has become ubiquitous in modern cities.",
      noun: "The ubiquity of smartphones transformed communication.",
      verb: "",
      adjective: "Ubiquitous social media algorithms influence behavior.",
      adverb: "She ubiquitously appears in social settings.",
    },
    synonyms: ["omnipresent", "pervasive", "universal", "everywhere"],
    antonyms: ["rare", "scarce", "limited", "localized"],
    relatedWords: ["omnipresent", "pervasive", "universal", "everywhere"],
    tags: ["Presence", "Modern", "Advanced"],
  },
  {
    word: "Vitriolic",
    definition: "Extremely harsh, bitter, or abusive; containing vitriol",
    root: "vitriolum (Latin) - sulfuric acid",
    forms: {
      noun: "vitriol",
      verb: "",
      adjective: "vitriolic",
      adverb: "vitriolically",
    },
    examples: {
      base: "The critic's vitriolic review destroyed the film's reputation.",
      noun: "His online comments were full of vitriol.",
      verb: "",
      adjective: "Vitriolic attacks on social media are increasingly common.",
      adverb: "She vitriolically denounced the proposal.",
    },
    synonyms: ["harsh", "bitter", "caustic", "acerbic"],
    antonyms: ["kind", "gentle", "mild", "sweet"],
    relatedWords: ["acerbic", "caustic", "bitter", "harsh"],
    tags: ["Communication", "Negative", "Criticism"],
  },
  {
    word: "Zealous",
    definition: "Showing great energy or enthusiasm for a cause; fervent",
    root: "zelus (Latin) - zeal, ardor",
    forms: {
      noun: "zeal",
      verb: "",
      adjective: "zealous",
      adverb: "zealously",
    },
    examples: {
      base: "The zealous volunteers worked tirelessly for the charity.",
      noun: "His zeal for the mission inspired the team.",
      verb: "",
      adjective: "Zealous competitors gave their all in the tournament.",
      adverb: "She zealously pursued her artistic dreams.",
    },
    synonyms: ["enthusiastic", "fervent", "passionate", "ardent"],
    antonyms: ["apathetic", "indifferent", "disinterested", "lukewarm"],
    relatedWords: ["enthusiastic", "fervent", "passionate", "ardent"],
    tags: ["Personality", "Positive", "Emotion"],
  },
  {
    word: "Ambivalent",
    definition: "Having mixed feelings or contradictory ideas about something",
    root: "ambi (Latin) - both, valens - strong",
    forms: {
      noun: "ambivalence",
      verb: "",
      adjective: "ambivalent",
      adverb: "ambivalently",
    },
    examples: {
      base: "She felt ambivalent about accepting the job offer.",
      noun: "His ambivalence made it hard to make a decision.",
      verb: "",
      adjective: "Ambivalent feelings are natural in difficult situations.",
      adverb: "He ambivalently agreed to the compromise.",
    },
    synonyms: ["conflicted", "uncertain", "indecisive", "mixed"],
    antonyms: ["certain", "decisive", "committed", "clear"],
    relatedWords: ["conflicted", "uncertain", "indecisive", "torn"],
    tags: ["Emotion", "Psychology", "Intermediate"],
  },
  {
    word: "Aesthetic",
    definition: "Relating to beauty or the appreciation of beauty; artistic",
    root: "aestheticos (Greek) - of sensation, of beauty",
    forms: {
      noun: "aesthetics",
      verb: "",
      adjective: "aesthetic",
      adverb: "aesthetically",
    },
    examples: {
      base: "The aesthetic of minimalism appeals to many designers.",
      noun: "Aesthetics is the study of beauty and taste.",
      verb: "",
      adjective: "The aesthetic design of the chair earned awards.",
      adverb: "The room was aesthetically pleasing.",
    },
    synonyms: ["artistic", "beautiful", "stylish", "tasteful"],
    antonyms: ["ugly", "unsightly", "unattractive", "garish"],
    relatedWords: ["artistic", "beautiful", "stylish", "tasteful"],
    tags: ["Beauty", "Art", "Intermediate"],
  },
];

export const sampleDataCarousel = [
  "Eloquent",
  "Ephemeral",
  "Pragmatic",
  "Meticulous",
  "Resilient",
  "Benevolent",
  "Ubiquitous",
  "Sagacious",
  "Serendipitous",
  "Zealous",
];
